version: '1'
services:
  amule:
    image: synopsis8/raspberrypi3-amule
    ports:
      - "4711:4711"
      - "4712:4712"
      - "8004:8004"
      - "8006:8006/udp"
      - "8007:8007/udp"
    environment:
      - PUID=0
      - GUID=0
    networks:
      amule:
        aliases:
          - amule
    volumes:
      - /storage/amule/conf:/home/amule/.aMule
      - /storage/amule/incoming:/incoming
      - /storage/amule/tmp:/temp
networks:
  amule:

